FROM nvcr.io/nvidia/tensorflow:21.09-tf2-py3

RUN cd /usr/src && \
    rm -rf app && \
    git clone --recurse-submodules https://github.com/spyysalo/keras-bert-ner.git app

WORKDIR /usr/src/app

RUN wget http://dl.turkunlp.org/turku-ner-models/combined-ext-model-130220.tar.gz && \
  tar xvzf combined-ext-model-130220.tar.gz && \
  rm combined-ext-model-130220.tar.gz

RUN pip install flask keras-bert

COPY preproc_finer .
