FROM python:3

RUN cd /usr/src && \
    rm -rf app && \
    git clone --recurse-submodules https://github.com/spyysalo/keras-bert-ner.git app

WORKDIR /usr/src/app
ENV VIRTUAL_ENV=/usr/src/app/venv-tnpp
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN ./scripts/get-models.sh

CMD python3 predict.py
